version: '2'
services:
  game:
    build: .
    #image: zopanix/factorio:v0.13.16-experimental
    volumes:
      - ${FACTORIO_SAVES_DIR}:/opt/factorio/saves:Z
      - ${FACTORIO_MODS_DIR}:/opt/factorio/mods:Z
    ports:
      - "34197:34197/udp"
    environment:
    networks:
      - factorio_net
    restart: always

