version: '2'
services:
  game:
    build: .
    #image: zopanix/factorio:v0.13.13-experimental
    volumes:
      - ./saves:/opt/factorio/saves
      - ./mods:/opt/factorio/mods
    ports:
      - "34197:34197/udp"
    environment:
      - FACTORIO_AUTOSAVE_INTERVAL=10
      - FACTORIO_AUTOSAVE_SLOTS=15
      - FACTORIO_ALLOW_COMMANDS=false
      - FACTORIO_NO_AUTO_PAUSE=false
    networks:
      - factorio_net
    restart: always

networks:
  factorio_net:
    driver: bridge
